return {
	"yorik1984/newpaper.nvim",
	lazy = true,
	priority = 1000,

	opts = {
		style = "dark",
		lightness = -0.08,
		saturation = 0.9,
		greyscale = false,
		editor_better_view = true,
		terminal            = "contrast",
		sidebars_contrast   = {},
		contrast_float      = true,
		contrast_telescope  = true,
		operators_bold      = false,
		delimiters_bold     = false,
		brackets_bold       = false,
		delim_rainbow_bold  = false,
		booleans            = "italic",
		keywords            = "bold",
		regex               = "bold",
		regex_bg            = true,
		tags                = "bold",
		tags_brackets_bold  = true,
		tex_major           = "bold",
		tex_operators_bold  = true,
		tex_brackets_bold   = false,
		tex_math_delim_bold = false,
		tex_keywords        = "italic",
		tex_zone            = "italic",
		tex_arg             = "italic",
		error_highlight     = "undercurl",
		italic_strings      = true,
		italic_comments     = true,
		italic_doc_comments = true,
		italic_functions    = false,
		italic_variables    = false,
		borders             = true,
		disable_background  = false,
		lsp_virtual_text_bg = true,
		hide_eob            = false,
		colors              = {},
		colors_advanced     = {},
		custom_highlights   = {},
		lualine_bold        = false,
		lualine_style       = "dark",
		devicons_custom     = {},
	},
}
