# Libraries
brew "ncurses"
brew "qt"

# Terminal tools
brew "make"
brew "cmake"
brew "cmake-docs"
brew "doxygen"
brew "git"
brew "graphviz"
cask "mactex-no-gui"
brew "pygments"
brew "watch"
brew "rustup"
brew "rsync"
# brew "entr" # run command on file change
brew "pngcheck"
brew "pngcrush"
# GNU
brew "coreutils"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "findutils"
brew "sheldon"
brew "btop"
brew "imagemagick"
brew "nmap"
brew "pyenv"
brew "tmux"
brew "less"
brew "tree"
brew "wget"
brew "zip"
brew "unzip"
cask "rar"

# Music
# brew "shntool"
# brew "musicbrainz-picard"
# brew "foobar2000"
# brew "scrcpy"

# Neovim
brew "neovim"
brew "ripgrep"
brew "bash-language-server"
brew "lua-language-server"
brew "cmake-language-server"
brew "vscode-langservers-extracted"
brew "pyright"

# GUI
cask "drawio"
cask "font-iosevka-nerd-font"
cask "freecad"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "keycastr"
cask "mos"
cask "prismlauncher"
cask "steam"
cask "telegram"
cask "discord"
cask "spotify"
cask "wezterm"
cask "xonotic"
cask "xquartz"
cask "syncthing"
cask "sanesidebuttons"
tap "homebrew-zathura/zathura"
brew "zathura --with-synctex"
