vim.g.fzf_action = {
	["ctrl-t"] = 'tab split',
	["ctrl-s"] = 'split',
	["ctrl-v"] = 'vsplit'}
vim.g.fzf_layout = {window = {width = 0.9, height = 0.6, relative = true }}
vim.g.fzf_colors = {
	fg =      {'fg', 'Normal'},
	bg =      {'bg', 'Normal'},
	hl =      {'fg', 'Comment'},
	['fg+'] = {'fg', 'CursorLine', 'CursorColumn', 'Normal'},
	['bg+'] = {'bg', 'CursorLine', 'CursorColumn'},
	['hl+'] = {'fg', 'Statement'},
	info =    {'fg', 'PreProc'},
	border =  {'fg', 'Ignore'},
	prompt =  {'fg', 'Conditional'},
	pointer = {'fg', 'Exception'},
	marker =  {'fg', 'Keyword'},
	spinner = {'fg', 'Label'},
	header =  {'fg', 'Comment'}}
vim.g.fzf_history_dir = '~/.local/share/fzf-history'
