general {
	lock_cmd = pidof hyprlock || hyprlock      # prevent multiple instances
	before_sleep_cmd = loginctl lock-session   # lock before any suspend
	after_sleep_cmd = hyprctl dispatch dpms on # optional: turn screen back on after resume
}
listener { 
	timeout = 600
	on-timeout = loginctl lock-session
}

listener { 
	timeout = 630
	on-timeout = pactl list sinks | grep -A 9 "State:" | grep -q "RUNNING" &&
		echo "Something is playing" || hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}
