-- Loads the machine half of the calling file's config: for <name>.lua, runs
-- ~/.config/hypr-local/<name>.lua if it exists. That directory is generated by
-- nix (dotfiles.hyprland.localConfig), not part of the repo.
function load_local_config()
	local info = debug.getinfo(2, 'S')
	if not info or info.source:sub(1, 1) ~= '@' then return false end
	local name = info.source:sub(2):match('([^/]+)%.lua$')
	if not name then return false end
	local xdg = os.getenv('XDG_CONFIG_HOME') or (os.getenv('HOME') .. '/.config')
	local chunk = loadfile(xdg .. '/hypr-local/' .. name .. '.lua')
	if not chunk then return false end
	chunk()
	return true
end
