#!/bin/bash
# Toggle this host's secondary monitor on/off. Which monitor and its
# per-orientation hl.monitor args come from hypr-local/secondary_display.sh,
# generated by nix (dotfiles.hyprland.secondaryDisplay). Hosts without one just
# get a notification.

NID=7493270
LOCAL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/hypr-local/secondary_display.sh"

if [ ! -f "$LOCAL_CONFIG" ]; then
	notify-send -r $NID -u low -a hyprctl "󰹑 " "No secondary display configured for this host"
	exit 1
fi
source "$LOCAL_CONFIG"

ORIENTATION=$1
ARGS_VAR="${ORIENTATION}_args"
MONITOR_ARGS="${!ARGS_VAR}"
if [ -z "$MONITOR_ARGS" ]; then
	echo "Usage: $0 {horizontal|vertical|mirror}" >&2
	exit 1
fi

hyprctl monitors | grep -q "$SECONDARY_MONITOR"
IS_ENABLED=$?

if [ $IS_ENABLED = "0" ]; then
	hyprctl eval "hl.monitor({output='$SECONDARY_MONITOR', disabled=true})" &&
		notify-send -r $NID -u low -a hyprctl "󰹑  󰨙 " "External monitor OFF"
else
	hyprctl eval "hl.monitor({output='$SECONDARY_MONITOR', $MONITOR_ARGS})" &&
		notify-send -r $NID -u low -a hyprctl "󰹑  󰨚 " "External monitor ON"
fi
