#!/bin/bash
# Toggle this host's secondary monitor on/off. Which monitor and its
# per-orientation hl.monitor args come from hypr-local/secondary_display.sh,
# generated by nix (dotfiles.hyprland.secondaryDisplay). Hosts without one just
# get a notification.

LOCAL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/hypr-local/secondary_display.sh"

notify() {
	local id_file=${XDG_RUNTIME_DIR:-/tmp}/secondary-display-notify-id
	local id
	id=$(cat "$id_file" 2>/dev/null)
	notify-send -p -u low -a hyprctl ${id:+-r "$id"} "$@" > "$id_file"
}

if [ ! -f "$LOCAL_CONFIG" ]; then
	notify "󰹑 " "No secondary display configured for this host"
	exit 1
fi
source "$LOCAL_CONFIG"

ORIENTATION=$1
ARGS_VAR="${ORIENTATION}_args"
MONITOR_ARGS="${!ARGS_VAR}"
if [ -z "$MONITOR_ARGS" ]; then
	echo "Usage: $0 {horizontal|vertical|mirror}" >&2
	exit 1
fi

hyprctl monitors | grep -q "$SECONDARY_MONITOR"
IS_ENABLED=$?

if [ $IS_ENABLED = "0" ]; then
	hyprctl eval "hl.monitor({output='$SECONDARY_MONITOR', disabled=true})" &&
		notify "󰹑  󰨙 " "External monitor OFF"
else
	hyprctl eval "hl.monitor({output='$SECONDARY_MONITOR', $MONITOR_ARGS})" &&
		notify "󰹑  󰨚 " "External monitor ON"
fi
