context.properties = {
    default.clock.rate = 44100
    default.clock.allowed-rates = [ 44100 ]
    default.clock.quantum = 256
    default.clock.min-quantum = 256
    default.clock.max-quantum = 256
}
