# There is only MacOS stuff, dont reference
# this file from linux machine

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Export GNUbin utils begore Mac's (grep stuff)
export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"

# Export GNU coreutil before Mac coreutils
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:${MANPATH}"
alias ls='ls --color=auto'
