export ZSH_CONFIG="$HOME/.config/zsh"

source $ZSH_CONFIG/exports.zsh
source $ZSH_CONFIG/plugins.zsh
source $ZSH_CONFIG/aliases.zsh
source $ZSH_CONFIG/visuals.zsh
source $ZSH_CONFIG/binds.zsh
source $ZSH_CONFIG/options.zsh
source $ZSH_CONFIG/completions.zsh
