export ZSH_CONFIG="$HOME/.config/zsh"

source $ZSH_CONFIG/exports.zsh
source $ZSH_CONFIG/aliases.zsh
source $ZSH_CONFIG/visuals.zsh
source $ZSH_CONFIG/binds.zsh
source $ZSH_CONFIG/options.zsh
if [ ! -f "$ZSH_CONFIG" ]; then
	source $ZSH_CONFIG/secrets.zsh
fi

eval "$(sheldon source)"

# more details: man pyenv
if command -v pyenv 1>/dev/null 2>&1; then
	eval "$(pyenv init -)"
fi
