monitor.alsa.rules = [
	{
		matches = [
			{
				node.name = "~alsa_output.*Qudelix.*"
			}
		],
		actions = {
			update-props = {
				audio.format = "S24LE",
				audio.rate = 96000
			}
		}
	},
	{
		matches = [
			{
				node.nick = "Mi Monitor"
			}
		],
		actions = {
			update-props = {
				audio.format = "24",
				audio.rate = 48000
			}
		}
	}
	{
		matches = [
			{
				node.nick = "SAMSUNG"
			}
		],
		actions = {
			update-props = {
				audio.format = "S24_LE",
				audio.rate = 48000
			}
		}
	}
]
