monitor.alsa.rules = [
	{
		matches = [
			{
				node.name = "~alsa_output.*Qudelix.*"
			}
		],
		actions = {
			update-props = {
				audio.format = "S24LE",
				audio.rate = 96000
			}
		}
	},
	{
		matches = [
			{
				node.nick = "Mi Monitor"
			}
		],
		actions = {
			update-props = {
				# api.alsa.period-size = 4096
				# api.alsa.headroom = 16384
				audio.format = "S16LE",
				audio.rate = 48000
			}
		}
	}
]
